[package]
name = "cinter_gui"
version = "4.1.0"
authors = ["Aske Simon Christensen <askesc@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
eframe = "0.18.0"
cpal = "0.11.0"
rand = "0.8"

cinter = { path = "../cinter" }
