[package]
name = "Cinter"
version = "4.0.0"
authors = ["Aske Simon Christensen <askesc@gmail.com>"]
edition = "2018"

[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }
nfd = "0.0.4"

[lib]
name = "cinter"
crate-type = ["cdylib"]
