[package]
name = "cinter"
version = "4.0.0"
authors = ["Aske Simon Christensen <askesc@gmail.com>"]
edition = "2018"

[dependencies]
vst = "0.2.0"
nfd = { git = "https://github.com/saurvs/nfd-rs.git" }

[lib]
crate-type = ["cdylib", "lib"]
